name: boilerplate
description: A Flutter boilerplate project with Provider, Firebase and Feature-Based Architecture.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Armazenamento Local
  shared_preferences:

  # API Service
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
